# Generated by Django 4.2 on 2023-12-09 18:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('krishna', '0006_auto_20200808_1207'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stations',
            fields=[
                ('S_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Latitude', models.CharField(blank=True, max_length=10, null=True)),
                ('Longitude', models.CharField(blank=True, max_length=10, null=True)),
                ('City', models.CharField(blank=True, max_length=10, null=True)),
                ('State', models.CharField(blank=True, max_length=10, null=True)),
                ('Country', models.CharField(blank=True, max_length=10, null=True)),
                ('Owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
