# Generated by Django 4.2 on 2023-12-09 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krishna', '0007_stations'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slots',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateField()),
                ('slot1', models.BooleanField()),
                ('slot2', models.BooleanField()),
                ('slot3', models.BooleanField()),
                ('slot4', models.BooleanField()),
                ('slot5', models.BooleanField()),
                ('slot6', models.BooleanField()),
                ('slot7', models.BooleanField()),
                ('slot8', models.BooleanField()),
                ('slot9', models.BooleanField()),
                ('slot10', models.BooleanField()),
                ('slot11', models.BooleanField()),
                ('slot12', models.BooleanField()),
            ],
        ),
    ]
